proxy:
  secretToken: "<RANDOM_HEX>"

auth:
  type: dummy
  dummy:
    password: 'CADRE'
  whitelist:
    users:
      - IUNItester
      - 2ndTester

auth:
  admin:
    users:
      - IUNItester
          
singleuser:
  # Get the latest image tag at:
  # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
  # https://hub.docker.com/r/anjia0532/kubeflow-images-public.tensorflow-1.4.1-notebook-gpu/tags
  # Inspect the Dockerfile at:
  # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
  image:
  name: jupyter/minimal-notebook
  tag: 7f1482f5a136
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:7f1482f5a136
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:7f1482f5a136
    - display_name: "Tensorflow environment"
      description: "The Jupyter Stacks TF image with CPU"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:7f1482f5a136
    - display_name: "Dedicated, 2 CPU cores & 13GB RAM, 1 NVIDIA Tesla K80 GPU"
      description: "By selecting this choice, you will be assigned a environment that will run on a dedicated machine with a single GPU, just for you."
      kubespawner_override:
        image: consideratio/singleuser-gpu:v0.3.0
        extra_resource_limits:
          nvidia.com/gpu: "1"
